ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'PAID';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'ADVANCE';
UPDATE "leaves" SET "leaveType" = 'PAID' WHERE "leaveType"::text IN ('SICK', 'ANNUAL', 'EMERGENCY', 'OTHER');
